### ISSUE TITLE
home icon

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#176]
## The Problem
Usability point of view, Every time a user wants to go to home page he/she has to open the side menu and click on home.

## The Solution
Can you offer an icon that links to the home page directly, place it near to search or sidebar icon.

**Comment by alistair3149** [comment]
It is by design to not have home page button always visible. One of the core design principles of Citizen is to take away distractions from reading the page. Unlike most websites, the main/home page on a wiki is rarely in the user flow.

The condition might change but so far there isn't a compelling reason to do so.
