### ISSUE TITLE
Gallery images are very large and blurry

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#413]
Image galleries with the "mode=packed" parameter are spanning the full width of the screen. Unfortunately the images aren't a high enough resolution and so they're blurry on my 1920x1080 display. The Star Citizen wiki itself uses a gallery template instead of the built in MediaWiki gallery so doesn't have this problem. Here is an example page: https://coasterpedia.net/wiki/Alligator_Island?useskin=citizen

If I remove the CSS added by Citizen then the images return to the normal size and while they are sharp, they are now pretty small. Would it be possible to have Citizen skin or the gallery feature draw higher-res images from the server?

**Comment by alistair3149** [comment]
Sorry for the late reply, have been busy the last month. Do you have a screenshot of the page? I can't reproduce the sharpness problem on my end.

**Comment by lachlanshanks** [comment]
No worries. Sorry, I should have clarified that the blurrriness on that article only becomes apparent if you turn the screen width up. 
![image](https://user-images.githubusercontent.com/7083224/150701942-a58bb5c0-7655-4572-9308-50d9791eca81.png)
However on this article, one of the images is blurry on the default screen width:
![image](https://user-images.githubusercontent.com/7083224/150701925-85e044ff-4aa3-4b20-8063-0e092935e5f2.png)
(Article: https://coasterpedia.net/wiki/Corkscrew_(Valleyfair)?useskin=citizen)

**Comment by octfx** [comment]
This is due to the skin styling galleries using flexbox.  
Each gallery entry has a setting of `flex-grow: 1`, which makes the element as big as possible.

In this case the last image won't fit the row, so the flexbox puts it into its own row. Due to the `grow` setting, the element is sized to fit the width of the gallery.

The widths of the images are determined before applying any styling (I think), i.e. mediawiki tries to fit four images into one row thus using relatively small image widths of `225px`.

After the styling is applied the previously mentioned flexbox condition is triggered.  
The image is blurry, because in reality it is only `225px` wide, but the flexbox resizes it to be ~`600px` wide, thus making it blurry.

You could either add some extra css to `MediaWiki:Citizen.css` to change this behaviour, like
```css
li.gallerybox {
    flex-basis: 24%;
}
```
which would ensure that four images are in each row, or you could add one more image to the gallery which would make the last row contain two images.

**Comment by lachlanshanks** [comment]
Unfortunately that doesn't fix it, at least not in every case. I think the default way for handling galleries would work okay. I tried CSS to override the gallery changes but I can't get it working quite right. Citizen is changing the width of the images. Is there a way to have Citizen fetch a higher-res version while also limiting the width so that it never tries to upscale an image beyond its native resolution?

**Comment by lachlanshanks** [comment]
I have modified my wiki's Citizen skin by doing this (https://github.com/lachlanshanks/mediawiki-skins-Citizen/commit/d30c8959f73c0188075b5a2bab905cf7c7b221a1) and also adding this to Common.css:

```
.gallerybox img,
.gallerybox {
	width:initial !important;
}
```

**Comment by alistair3149** [comment]
> Unfortunately that doesn't fix it, at least not in every case. I think the default way for handling galleries would work okay. I tried CSS to override the gallery changes but I can't get it working quite right. Citizen is changing the width of the images. Is there a way to have Citizen fetch a higher-res version while also limiting the width so that it never tries to upscale an image beyond its native resolution?

To my understanding, it might be too complicated to implement for me as I'm not familiar with the how gallery work with MediaWiki core. Currently it is not the skin's responsibility to fetch the images, but MW core. There might be things that could be done but I'm not familiar with it.

**Comment by lachlanshanks** [comment]
> 

Thanks for clarifying. For me I think it would be best just to handle the galleries the same way Vector does, though I know that's just my opinion on it. I'd rather have a small image than large and blurry one
