### ISSUE TITLE
Visual Editor incompatability, missing icons for page actions

### ISSUE THREAD

**Issue by ChaoticShadow** [StarCitizenTools/mediawiki-skins-Citizen#435]
## Describe the Bug
On every single page, there are no icons for the page actions. From what I can tell it's because selectors `#ca-history` are missing so the CSS doesn't apply. Because `#ca-edit` is missing, the skin is also no longer compatible with Visual Editor.

1. Go to [https://projectsekai.miraheze.org/wiki/Main_Page](https://projectsekai.miraheze.org/wiki/Main_Page)
2. Visit any page
3. Icons for Edit, Edit Source, History, etc. buttons are missing, and Visual Editor fails to work

## System
_Please complete the following information:_
 - MediaWiki version: 1.37.1 (2d847ba)
 - Server OS: Debian 11
 - Installed extensions and versions: [See here](https://projectsekai.miraheze.org/wiki/Special:Version)
 - PHP version: 7.4.28 (fpm-fcgi)

**Comment by lachlanshanks** [comment]
I noticed this when I tried updating my skin, and so I rolled mine back. Appears to be a problem with the latest version.

**Comment by RhinosF1** [comment]
Issue seen at Miraheze, given what we deployed. Quite possibly https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/3e6a240c4852f120ab787c45b922d36afa9a3869

**Comment by RhinosF1** [comment]
I've pinged Jon on IRC

**Comment by alistair3149** [comment]
It seems that there are some changes related to core or VE that changed that. I haven't been following the development for a while and would need some time to troubleshoot it.

**Comment by lens0021** [comment]
This is not related to VE. I've `git bisect`ed on a vanilla installation of MediaWiki without even VE and

> 3e6a240c4852f120ab787c45b922d36afa9a3869 is the first bad commit

**Comment by RhinosF1** [comment]
> This is not related to VE. I've `git bisect`ed on a vanilla installation of MediaWiki without even VE and
> 
> > [3e6a240](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/3e6a240c4852f120ab787c45b922d36afa9a3869) is the first bad commit

I pinged Jon when this was first reported to say that.

**Comment by lens0021** [comment]
After the commit, SkinCitizen fetches the portlet data from `SkinTemplate::runOnSkinTemplateNavigationHooks()` which is called in `SkinTemplate::buildContentNavigationUrlsInternal()`, But `ca-$ID`s are set after the calling.

To fix this, there are two possible ways:

- Set ID manually in `SkinCitizen::runOnSkinTemplateNavigationHooks()`
- Use `SkinMustache::getTemplateData()['data-portlets']['data-views']` instead of the data fetched from the hook.

I think the second one is more modern. However, it seems to contain additional HTML changes and the page tools are displayed below after I edited:

![image](https://user-images.githubusercontent.com/28209361/163181019-ec0448c7-095d-48af-b20b-222c01eb4bba.png)

Anyway, I will submit a PR when I fix the additional styles.
