### ISSUE TITLE
Minor inconsistencies in 2.0.0-beta.0

### ISSUE THREAD

**Issue by octfx** [StarCitizenTools/mediawiki-skins-Citizen#527]
Some things that I've noticed in 2.0.0-beta.0 :)

## z-index for `.mw-body-header`
The sticky header has a z-index of 1. This may generally be fine(?), but other content elements may "leak" over it.  
![image](https://user-images.githubusercontent.com/6594492/193558093-760c2411-c0da-459f-a862-8ae8947186a1.png)
This could be remedied by setting a relatively high z-index as a preventive measure

## Main content padding
The main content `.citizen-body` has a right padding corresponding to the toc width.
![image](https://user-images.githubusercontent.com/6594492/193558563-78386f69-9aba-49bd-b604-3ca4818185dc.png)
I don't know if this is intentional, but using the default settings, the page isn't centered anymore

## Header preferences
The preference menu from the header seems to be wrongly aligned.
![image](https://user-images.githubusercontent.com/6594492/193558795-22c80641-7fde-4b45-a49f-f149f16aeeba.png)
Screenshot show the left edge of the screen, the preferences, `#citizen-pref-panel -> left: unset` seems to cause the alignment

---
Thank you very much for your work on Citizen 2.0, I really like the new style :)

**Comment by alistair3149** [comment]
Glad that you like it, and really thank you very much for testing and using it!

**z-index for .mw-body-header**
That should be an easy fix, will be patched soon.

**Main content padding**
Yes it is intentional for pages with ToC. So ToC + Content will be considered a block and align at the middle.
The current implementation looks a bit hacky because ToC can't not be rendered by skin on some older versions off MediaWiki.
However, all these CSS hacks will be dropped when we target 1.39 so it should always work.

**Header preferences**
It might be stale cache on the wiki, the styles loaded on your wiki seemed to be different from my local build for that element.

**Comment by alistair3149** [comment]
Should be fixed now. Closing the issue
