### ISSUE TITLE
Page Too Wide On iOS Devices

### ISSUE THREAD

**Issue by iAdam1n** [StarCitizenTools/mediawiki-skins-Citizen#555]
As the photo shows, the latest version of Citizen doesn’t fit correctly on iOS devices (I’m using an iPhone 12). Changing page width doesn’t help either. 
![ADB8790B-12B3-4999-82E8-4D9023B1CE84](https://user-images.githubusercontent.com/2139641/206095636-541ca2b6-183d-4660-9c6b-2263601b6a78.jpeg)

**Comment by alistair3149** [comment]
That's very weird. Do you have the exact URL of the page? It looks like the old version of the RecentChanges page but I don't know how to activate it

**Comment by iAdam1n** [comment]
@alistair3149 the wiki is not yet public so can’t share the URL. The option is in Preferences>Recent Changes>Use non-JavaScript interface.

Also noticed the hamburger menu is chopped off too. 
![2731EB86-191A-4B92-A81F-EAA1209985A0](https://user-images.githubusercontent.com/2139641/206097140-5c29b95b-c414-4e77-aaa8-d7ccd0af6d2f.jpeg)

**Comment by alistair3149** [comment]
I'll take a look tomorrow.

I haven't tweaked the old RC page so I suspect that there's an element overflowing the page and breaking the layout.

**Comment by alistair3149** [comment]
Okay I double checked and compared to setups.

I fixed the menu issue with [71d89bc](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/71d89bc935bae8b94534cba477cffa84ac999a4e). 

As for the form overflow, it is caused by the font size styles under `MediaWiki:Common.css` under `@media only screen and (max-device-width: 600px)` broke the layout. Under normal circumstances, it wraps correctly.

**Comment by iAdam1n** [comment]
Thanks!
