### ISSUE TITLE
Make TOC Optionally Collapsible

### ISSUE THREAD

**Issue by iAdam1n** [StarCitizenTools/mediawiki-skins-Citizen#556]
The TOC can be annoying to see at times as it blocks view that could be used for something else. I'd like to suggest making it optionally collapsible like you can do with sections.

**Comment by alistair3149** [comment]
The content shouldn't overflow to the TOC area (i.e. blocking view) in normal circumstances. Do you have examples of the issue?

**Comment by iAdam1n** [comment]
I mean it doesn't overflow as such, but what I mean is if you collapsed it then you could see more content on the page. For example, more of the width of this table could be shown if it's collapsed. 
<img width="1670" alt="Screenshot 2022-12-10 at 07 00 16" src="https://user-images.githubusercontent.com/2139641/206836529-d4ad933d-4080-4ff3-86f7-0a398d75be52.png">

**Comment by alistair3149** [comment]
Yeah it is overflowing since the table has overflowed the content container/grid cell, that's why it gets cut off.
You can see a similar issue with Vector 2022, where the table is cut off as well.

One of the solution that I have been looking into is to add optional responsive table support, but I am still looking into it.

**Comment by iAdam1n** [comment]
We've made the table scrollable on our wiki but my suggestion would be it'd be nice to be able to just collapse the TOC if you want to. That way you can see the rest of the table (if I'm not mistaken?)

**Comment by alistair3149** [comment]
I'll see what I can do about it!
