### ISSUE TITLE
Help Icon Not Showing On Sidebar

### ISSUE THREAD

**Issue by iAdam1n** [StarCitizenTools/mediawiki-skins-Citizen#560]
I'm not sure if this is a CSS issue with something we've set that conflicts with Citizen or a Citizen bug but as the screenshot shows, the help icon is missing. The URL for you to check it out is https://theapplewiki.com.
<img width="602" alt="Screenshot 2022-12-21 at 18 37 16" src="https://user-images.githubusercontent.com/2139641/208979062-ef4ac4f2-6135-4aba-b575-67b4f6a37e20.png">

**Comment by alistair3149** [comment]
Thanks for the report! It should now be fixed.
Please let me know if it is fixed for you and I can close the issue.

**Comment by iAdam1n** [comment]
Thanks! I can confirm that fixed it. I noticed on https://starcitizen.tools/ you have an icon for Special pages but it's not in the file you just updated. Not sure if that's intentional or not but figured I'd mention it.

**Comment by alistair3149** [comment]
> Thanks! I can confirm that fixed it. I noticed on https://starcitizen.tools/ you have an icon for Special pages but it's not in the file you just updated. Not sure if that's intentional or not but figured I'd mention it.

Yes it is not in the current version anymore because of technical reason. We might drop the current icon functionality altogether from the sidebar/drawer since we can't target those links consistently, and many wikis just use icon fonts or emoji through MediaWiki:Sidebar.

It might be revisited in the future when we refactor the current menu system.

**Comment by iAdam1n** [comment]
Yeah no worries. I don't know if it's a cache thing or not but help icon is still not showing on Mediawiki: pages (such as sidebar, Common.js).
