### ISSUE TITLE
Compatibility issue in sections.js and tableOfContents.js

### ISSUE THREAD

**Issue by williamsp** [StarCitizenTools/mediawiki-skins-Citizen#576]
Hi, commit 9652d4f8ed1ceb943e57b6f0577c1d697619bf7f is causing some compatibility issue, like on IE or older version of Firefox where `??` operator is not supported yet.

![gambar](https://user-images.githubusercontent.com/3760416/214211554-d8b4fdeb-7727-48f1-bdca-27b6dc479608.png)

Can we change the code in `resources/skins.citizen.scripts.sections/skins.citizen.scripts.sections.js` and `resources/skins.citizen.scripts/tableOfContents.js` to something like this so it can support more browsers?
```js
headline = headings[i].querySelector('.mw-headline');
if (!headline) headline = headings[i].querySelector('.mw-heading');
```

**Comment by alistair3149** [comment]
There are also other parts of the skin that use [nullish coalescing operator](https://caniuse.com/mdn-javascript_operators_nullish_coalescing) (`??`) in JS.
For Citizen, we use features that is supported by at least 90% of browsers for easier development and maintenance. Since nullish coalescing operator fits the criteria, we will keep it as it is.
