### ISSUE TITLE
Hope the Last modified which describes author and relative time of last edit

### ISSUE THREAD

**Issue by Dome-World** [StarCitizenTools/mediawiki-skins-Citizen#700]
## The Problem
The time display is a bit unclear. I think last modified shows a countdown to the present time and describes author will greatly improving editor experience.

## The Solution
like [minerva-last-modified-date](https://github.com/wikimedia/mediawiki-skins-MinervaNeue/blob/11e09ea7b37854dad6e98ee863d8c6a3cf52351f/includes/Skins/SkinMinerva.php#L559) get a history link which describes author and relative time of last edit.

**Comment by alistair3149** [comment]
Will look into it. We are planning to enhance the history button into a popup menu filled with activities data related to the current page. The menu will contain things like contributors, last modified, etc. However, this is currently at a lower priority since the effort are focused on the search feature atm.

**Comment by alistair3149** [comment]
You can probably do it by modifying MediaWiki:Tagline and insert the revision data with magic words
