### ISSUE TITLE
Prevent body height change when .citizen-page-header--sticky is triggered

### ISSUE THREAD

**Issue by csalinezh** [StarCitizenTools/mediawiki-skins-Citizen#854]
## Describe the Bug
Currently `initStickyHeader` in [resources/skins.citizen.scripts/skin.js](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/v2.14.1/resources/skins.citizen.scripts/skin.js#L18) is used to trigger the sticky header on article pages. It adds a class `citizen-page-header--sticky`, which modifies `<header class="mw-body-header citizen-page-header">` to use `position: sticky`.

`position: sticky` elements retain their space in the original flow of boxes, therefore they should not cause reflow when becoming sticky. However, styles related to `.citizen-page-header--sticky` changes the height of that `<header>`, eventually changing the height of `<body>`. Users can notice a slight jump in the scroll bar when the sticky header appear or disappear.

1. Go to a random article on starcitizen.tools
2. Open Devtools and monitor the height of `<header class="mw-body-header citizen-page-header">` or its ancestors
3. Scroll down so the header becomes sticky

## Expected Behavior
It's a pretty minor issue (and only happens at the few instants that the sticky state changes), but solving it will eliminate layout shift during scroll on article pages.

I'm not sure if it can be solved without too much work. One way I can think of is wrapping the header in a fixed-size container, and only float its content out when needed.

## System
 - Citizen 2.14.1

**Comment by alistair3149** [comment]
Wrapping in the container probably won't work because sticky only sticks to the parent container.

I have made a few patch related to scrolling since I tagged 2.14.1 and it is less noticeable now, please let me know if you can still observe the issue.

If the issue is still noticeable, it can likely be solved by placing a placeholder element with a height difference between the non-sticky and sticky state of the header, but I am not sure if it is worth the effort.

**Comment by csalinezh** [comment]
By "container" I was referring to a plain `<div>`. It does not create a new stacking context, therefore elements with `position: sticky` will continue to stick to the viewport after being wrapped another layer.

Actually I noticed this height-changing issue when playing with the "paint flashing" tool in Chrome Devtools (Chrome 125). The whole screen flashes when the sticky header is toggled (I guess it's due to the height of `<body>` changes, which somehow triggers a re-paint). The paint count can also be seen in the "Layers" panel (although that panel looks a bit dilapidated and might not be accurate for recent versions of Chromium).

I tried slapping `.citizen-page-header {height: 80px;}` and it indeed limits the re-paint region to the header itself. The flame graph in "Performance" panel shows noticeable speed improvement for the "Pre-paint" and "Paint" events.

I acknowledge this feels micro-optimizing (albeit users can notice a jump in the scroll bar). You can consider it next time doing refactor to the sticky header design.

**Comment by software-2** [comment]
I'm running 2.15.1 on my MediaWiki install. When scrolling down juuuust right on certain displays, this height shift causes the sticky header to appear and disappear rapidly as it hits the bounds of the header being sticky/non-sticky. At least in my case, this issue creates a more pronounced impact than just a slight jump, since it renders the page unreadable while the rapid shifting occurs.

I can confirm that adding a static height inside `layout.less` does work around the issue.

**Comment by alistair3149** [comment]
The static height method won't work because the height of the element is dynamic, depending on the length of the page title and the viewport width.

I have made various patches to address the flickering issue. @software-2 can you reproduce the same issue with the latest patch? 

There are still a little layout shift in the current state. I will revisit it again in the future. In the meantime, please feel free to ideate or submit a PR if anyone have a solution!

**Comment by csalinezh** [comment]
Thank you for the effort! Currently the green area shown by the "paint flashing" tool is indeed more specific (unlike the full screen flash of green before).

---
However I would like to do an additional nitpicking: The "Performance" tab of Chrome DevTools shows `toggleStickyHeader` triggers a forced style recalculation: https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/29637e89ac24578e0ddf3c082fd006a9e23ad9e6/resources/skins.citizen.scripts/stickyHeader.js#L50-L51

I feel it's generally a problem that should be avoided, however I'm not sure if it actually matters here (no other concurrent task exists, which would be delayed by this synchronous job). Can general solution to this problem (caching the size values before changing style) be applied here?

**Comment by alistair3149** [comment]
Hmm I made a commit that should use a cached value. But even with a cached value, there would always be a style recalculation since the height of the sticky element changed.

The real way I can think of is to completely remove it is to clone or create a separate sticky header, and only show it when needed.

**Comment by csalinezh** [comment]
"Style recalculation" is not avoidable if the DOM or CSS changes. You can only try to make it faster for example via that CSS selector performance tool first introduced in Edge DevTools (available in Chrome since v125).
