### ISSUE TITLE
Missing Preferences

### ISSUE THREAD

**Issue by RothwellWiki** [StarCitizenTools/mediawiki-skins-Citizen#859]
### ~~Weird Drawer Behaviour~~ (Resolved by clearing cache)
_Included in case it's at all relevant to the preference thing._
~~The pictures speak for themselves, but, without me having recently changed any of the CSS or JS, the drawer seems to be all messed up. However, it is completely fine if I toggle mobile or desktop view manually. On mobiles, it seems to work fine, probably because it's toggled automatically.~~ This happened on multiple different browsers (Safari, Firefox & Brave) but clearing the cache seems to have resolved it on all.
![Toggle off](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/109766234/51a7cfd3-f5d3-4919-8b3f-f57b7331a4a1)
![Toggle on](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/109766234/a232081d-7fc0-4bb7-b3d7-9ea7ad854428) 
### Missing Preferences
The preferences don't show anything for some reason. This seems to have happened at the same time as the above but I think they're probably unrelated. It was not resolved by clearing the cache.  This is unaffected by toggling the view or being on mobile.
![Preferences](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/109766234/e8323f60-6fd1-4e9a-aa46-f5c27c79894f) 

### Steps to reproduce the behaviour:
1. Go to 'https://www.rothwell-leeds.co.uk/wiki/Main_Page'
2. Click preference wheel
3. See bug

## Expected Behaviour
The preferences menu should open.
## System
- MediaWiki version: 1.41.0
- Server OS: Unknown (hosted by Miraheze).
- Installed extensions and versions: see [Special:Version](https://www.rothwell-leeds.co.uk/wiki/Special:Version). Citizen 2.15.1 (dcd569f.)
- PHP version: 8.2.18 (fpm-fcgi)

**Comment by BlankEclair** [comment]
Interestingly, I was unable to reproduce this on a test server running MediaWiki commit [`5498056`](https://github.com/wikimedia/mediawiki/commit/5498056197823bef0498101442d9d8da9fa2a83d) and Citizen commit dcd569f (same versions as what is currently on Miraheze right now).

I did some debugging on a wiki using Citizen on Miraheze (more specifically, https://rainverse.wiki), and it appears that this condition is running all the time:

https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/a8daa82354dec287c6a329b20c93fe1a35d2e29f/resources/skins.citizen.preferences/clientPreferences.js#L287-L291

MediaWiki:Citizen-feature-custom-font-size-name on my test server outputs "Text", but that same page on Miraheze says that there is currently no text on that page.

Perhaps this issue is misdiagnosed? I'll try to dig into this

**Comment by BlankEclair** [comment]
Okay, this is odd... Miraheze is running a newer version of Citizen, but it is also running older i18n text.

It is at least running commit a741639085d70c22a9f49890542a142a223bf981, since https://meta.miraheze.org/w/load.php?debug=1&modules=skins.citizen.preferences includes the line `if ( !labelMsg.exists() && mw.config.get( 'wgUserLanguage' ) !== 'qqx' )`

However, it is also not running i18n strings from that commit, since Miraheze has https://meta.miraheze.org/wiki/MediaWiki:Prefs-citizen-theme-label (a key removed since that commit).

**Comment by BlankEclair** [comment]
Okay, this appears to be entirely a Miraheze issue. They updated the skin, but they forgot to update the [localisation cache](https://www.mediawiki.org/wiki/Manual:LocalisationCache.php) and they disabled automatic refreshing of the cache (via [`$wgLocalisationCacheConf['manualRecache'] = true`](https://www.mediawiki.org/wiki/Manual:$wgLocalisationCacheConf))
