### ISSUE TITLE
Column Headers for Cargo Dynamic Tables overlap sorting icon

### ISSUE THREAD

**Issue by TarkusLee** [StarCitizenTools/mediawiki-skins-Citizen#924]
When a Cargo Dynamic Table has many columns, the column headers become cramped and their text begins to overlap the sort buttons.

![image](https://github.com/user-attachments/assets/f0fc5b60-2a68-4f3a-8620-875cfee3b87f)

An example can be seen here: https://www.dustloop.com/w/GGACR/Venom/Frame_Data#Normals

**Comment by alistair3149** [comment]
It is a tough issue since DataTables (what Cargo uses for dynamic tables) should handle the responsiveness instead of the skin. That's how it is handled in other extensions that uses DataTables such as Semantic MediaWiki. Therefore, I am unsure on how to handle it properly.

Would you be able to [file an issue](https://phabricator.wikimedia.org/maniphest/task/edit/form/1/?projects=MediaWiki-extensions-Cargo) to the Cargo extension about supporting responsive design? This should also benefit other limited-width skins such as Vector 2022, Cosmos, etc.
